pipeline{
	agent any
	stages {
	  stage('checkout') {
	    steps {
     
			git 'https://github.com/chetanBGK/jenkins.git'

		    }
	  }

	  stage('Test') {
        	    when {
                	anyOf {
	                    branch 'master'
	                    branch 'test'
        	        	}
            		}
		steps {
	              sh '''
			cd javaapp-pipeline
			mvn test
			'''
	        	    }
	        	}

	  stage('Deploy') {
        		when {
	                	branch 'master'
        		    }
	            steps {
        	        sh '''
                	    cd javaapp-pipeline
				cd target
	                    echo "Deploying application..."
				
	                   java -jar target/java-sample-21-1.0.0.jar
	                '''
        		    }
		        }
  
		
	}
}
