pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Test') {
            when {
                anyOf {
                    branch 'master'
                    branch 'test'
                }
            }
            steps {
                sh '''
                    cd javaapp-pipeline
                    mvn test
                '''
            }
        }

        stage('Build') {
            when {
                branch 'master'
            }
            steps {
                sh '''
                    cd javaapp-pipeline
                    mvn clean package
                '''
            }
        }

        stage('Deploy') {
            when {
                branch 'master'
            }
            steps {
                sh '''
                    cd javaapp-pipeline
                    echo "Deploying application..."
                    java -jar target/java-sample-21-1.0.0.jar
                '''
            }
        }
    }
}
